"use client";
import { useParams } from "next/navigation";
import React, { useEffect, useRef } from "react";
import { useDoctorContext } from "@/context/DoctorContext";
import Image from "next/image";
import { assets } from "@/assets/assets_admin/assets";
import { useRouter } from "next/navigation";

const Patient = () => {
  const { appointments, getAppointments, dToken, currentPatient } =
    useDoctorContext();
  const { patient } = useParams();
  const ref = useRef<HTMLDivElement>(null);
  const router = useRouter();

  useEffect(() => {
    if (dToken) {
      getAppointments();
    }
  }, [dToken]);

  useEffect(() => console.log(currentPatient, appointments), [currentPatient]);

  return !appointments || !currentPatient ? ( router.back() ) : (
    <div>
      <div>
        <div
          ref={ref}
          className="flex justify-center items-center h-[1139px] w-[827px] scale-[40%] -translate-y-1/4 sm:scale-50 md:scale-75 md:-translate-y-[150px] lg:scale-100 lg:translate-y-0 shadow-[4px_4px_20px_4px_#1a202c] "
        >
          <div className="h-[90%] w-[90%] p-4">
            <Image src={assets.admin_logo.src} alt="logo" width={150} height={15} className="mx-auto mb-2"/>
            <h3 className="text-lg font-semibold">
              Date: {new Date().toLocaleDateString()}
            </h3>
            <div className="flex justify-between mt-2 pb-3 border-b-1 border-red-600">
              {/* Patient Info */}
              <div>
                <h2>  Patient name : <span className="defaultText">{currentPatient.name}</span></h2>
                <h2>  Contact :{" "}  <span className="defaultText">    {currentPatient.phone} | {currentPatient.email}  </span></h2>
                <h2>  Info :{" "}  <span className="defaultText">    {currentPatient.dob} | {currentPatient.gender}  </span></h2>
              </div>

              {/* Doctor Info */}
              <div>
                <h2 className="defaultText">Doctor name : <span className="defaultText">{appointments[0].docData.name}</span>                </h2>
                <h2> <span className="defaultText">{appointments[0].docData.educationDetails.degree} | {appointments[0].docData.educationDetails.college} </span></h2>
                <h2><span className="defaultText">{appointments[0].docData.experience} years experience </span> </h2>
                <h2><span className="defaultText">{appointments[0].docData.address.street} | {appointments[0].docData.address.pincode} | {appointments[0].docData.address.state}</span></h2>
              </div>
            </div>

            <div className="border-b-1 mt-1 border-red-600"></div>

            <div className="flex-center mx-auto my-6">
              <table className="w-[98%] md:w-[90%]">
                <thead>
                  <tr className="border">
                    <th className="border px-2 py-1">Product ID</th>
                    <th className="border px-2 py-1">Name</th>
                    <th className="border px-2 py-1">Quantity</th>
                    <th className="border px-2 py-1">Price per Unit &#8377;</th>
                    <th className="border px-2 py-1">Net Price &#8377;</th>
                  </tr>
                </thead>
              </table>
            </div>

            <div className="absolute bottom-[6%] left-1/2 w-[90%] -translate-x-1/2">
              <h3 className="smalltext mx-2 text-center tracking-tight text-gray-600">
                This is a computer generated prescription generated by the
                doctor after successful examining of the patient.
              </h3>
              <h3 className="smalltext mt-2 text-center font-semibold tracking-wide">
                © 2025 All Rights Reserved.
              </h3>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Patient;
